# cm's
HALF_VERTICAL_PART = 120
VERTICAL_PART = 220
HORIZONTAL_PART = 250
SMALL_HORIZONTAL_PART = 150
DIAGONAL_PART = 321.5
FOOT_PART = 65 # normally 50cm
HALF_FOOT_PART = 115 # normally 100cm
COMPLETE_FOOT_PART = 215 # normally 200cm
FOOT_INSIDE_PART = 15
FLOOR_SPACE = 15
SUPPORT_SPACE = 47

ADJUSTMENT_SHAFT1 = 50
ADJUSTMENT_SHAFT2 = 70
ADJUSTMENT_SHAFT3 = 100

# colors
STEEL_PLATFORM_COLOR = 1
ADJUSTMENT_COLOR = 2
FOOT_COLOR = 3
HORIZONTAL_COLOR = 4
VERTICAL_COLOR = 5
DIAGONAL_COLOR = 6
SURFACE_COLOR = 7
TEXT_COLOR = 7

TOP_CIRCLE_COLOR = 1
TOP_VERTICAL_COLOR = 6
TOP_PLATFORM_COLOR = 4
TOP_INNER_HORIZONTAL_COLOR = 9
TOP_OUTER_HORIZONTAL_COLOR = 8

# Top Down
SC_WIDTH = 70
CONSOLE_WIDTH = 35